# Dependencies
markdown:         redcarpet
highlighter:      pygments
plugins:          
- jekyll-paginate

# Permalinks
permalink:        pretty

# Setup
title:            Mute C0de
tagline:          'Audio Development'
description:      'audio & programming blog by yvan vander sanden'
url:              http://yvanvds.github.io
baseurl:          /

author:
  name:           'yvan vander sanden'
  url:            http://mutecode.com

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/yvanvds/yvanvds.github.io

# modifiers
excerpt_separator: "<!--more-->"
